name: Deploy Key Test

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: branch1

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
        
    # - name: Update known_hosts
    #   run: ssh-keyscan -H www.landl0ck3d.tk >> ~/.ssh/known_hosts

    - name: Deploy
      run: |
        ssh gridl0ck@www.landl0ck3d.tk 'cd /home/gridl0ck/test-github && git pull'
