name: Deploy Key Test

on: 
  workflow_dispatch:

permissions:
  contents: read
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: branch1
        
    - name: install ssh key
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H www.landl0ck3d.tk >> ~/.ssh/known_hosts

    - name: Fetch all branches
      run: git fetch --all

    - name: List branches
      run: |
        branches=$(git branch -r --list "origin/branch*" | cut -d '/' -f 2)
        branches=$(echo $branches | tr ' ' '\n') # Convert space-separated list to newline-separated
        echo "Branches to merge: $branches"

    # - name: Merge Branches
    #   run: |
    #     git checkout staging
    #     for branch in $branches; do
    #       git merge "origin/$branch"
    #     done

    # - name: Push changes to server
    #   run: |
    #     git push origin staging


    - name: Connect and Pull
      run: |
        ssh gridl0ck@www.landl0ck3d.tk -i ~/.ssh/id_rsa 'cd /home/gridl0ck/test-github && git checkout staging && for branch in $(git branch -r --list "origin/branch*" | cut -d "/" -f 2); do git merge "origin/$branch"; done'
        ssh gridl0ck@www.landl0ck3d.tk -i ~/.ssh/id_rsa "cd /home/gridl0ck/test-github && git push origin staging"

    - name: cleanup
      run: rm -rf ~/.ssh
